---
formatter: markdown table
version: '>= 0.16.0, < 1.0.0'

sort:
  enabled: true
  by: required

settings:
  # For Terraform configurations, use the .terraform.lock.hcl file to define the
  # documented versions of all providers, rather than the Terraform code itself
  lockfile: true
  read-comments: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- terraform-docs-start -->
    <!-- prettier-ignore-start -->

    {{ .Content }}

    <!-- prettier-ignore-end -->
    <!-- terraform-docs-end -->
