---
name: Label

on:
  pull_request:
    types:
      - labeled
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  checks: write
  pull-requests: write

jobs:
  remove-force-integrations-label:
    name: Remove Label
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'force-integrations-run' }}
    steps:
      - name: Remove the force-integrations-run Label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['force-integrations-run']
            })

  terraform-integrations:
    # This job name must match the name of call called Workflow in order for
    # the name to successfully match any required status checks within the
    # branch protections
    name: Terraform Integrations
    if: ${{ github.event.label.name == 'force-integrations-run' }}
    uses: ./.github/workflows/terraform-integrations.yaml
    secrets: inherit
